"""initial schema

Revision ID: 9350c570ff24
Revises: 
Create Date: 2026-08-31 18:20:13.886683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9350c570ff24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('external_customer_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_customer_id'), 'customers', ['external_customer_id'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('agent', 'supervisor', 'finance_approver', 'admin', name='userrole', native_enum=False, length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cases',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=True),
    sa.Column('trigger_type', sa.Enum('customer_contact', 'system_detected', 'manual', name='casetriggertype', native_enum=False, length=64), nullable=False),
    sa.Column('opened_by_user_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'pending_evidence', 'pending_approval', 'action_in_progress', 'pending_customer_update', 'closed', 'reopened', name='casestatus', native_enum=False, length=64), nullable=False),
    sa.Column('stage', sa.Enum('issue_reported', 'journey_assembled', 'failure_located', 'evidence_checked', 'impact_assessed', 'recovery_options_ranked', 'actions_coordinated', 'customer_updated', 'outcome_retained', name='journeystage', native_enum=False, length=64), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('needs_reevaluation', sa.Boolean(), nullable=False),
    sa.Column('primary_hypothesis_id', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_summary', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_hypothesis_id'], ['hypotheses.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_customer_id'), 'cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cases_order_id'), 'cases', ['order_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=True),
    sa.Column('source_type', sa.Enum('web_app_event', 'store_transaction', 'order', 'fulfillment_update', 'payment', 'contact_center_record', 'return', 'itsm_incident', name='sourcetype', native_enum=False, length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=256), nullable=False),
    sa.Column('provenance_source', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'ai_inference', 'human_input', 'automated_action', 'human_decision', name='actortype', native_enum=False, length=64), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate_of', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['is_duplicate_of'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['evidence_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_customer_id'), 'evidence_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_external_ref'), 'evidence_records', ['external_ref'], unique=False)
    op.create_index(op.f('ix_evidence_records_ingested_at'), 'evidence_records', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_evidence_records_occurred_at'), 'evidence_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_evidence_records_order_id'), 'evidence_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_source_type'), 'evidence_records', ['source_type'], unique=False)
    op.create_table('action_requests',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('request_evidence', 'run_analysis', 'execute_recovery', 'escalate_itsm', 'notify_customer', 'close_case', name='actiontype', native_enum=False, length=64), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.String(length=2048), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'pending_approval', 'approved', 'rejected', 'executing', 'succeeded', 'failed', 'needs_manual_review', name='actionstatus', native_enum=False, length=64), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_requests_case_id'), 'action_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_action_requests_idempotency_key'), 'action_requests', ['idempotency_key'], unique=True)
    op.create_table('audit_entries',
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'ai_inference', 'human_input', 'automated_action', 'human_decision', name='actortype', native_enum=False, length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_actor_type'), 'audit_entries', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_entries_case_id'), 'audit_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_entity_id'), 'audit_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_occurred_at'), 'audit_entries', ['occurred_at'], unique=False)
    op.create_table('canonical_events',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('evidence_record_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('web_app_event', 'store_transaction', 'order', 'fulfillment_update', 'payment', 'contact_center_record', 'return', 'itsm_incident', name='sourcetype', native_enum=False, length=64), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_record_id'], ['evidence_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_events_case_id'), 'canonical_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_canonical_events_effective_at'), 'canonical_events', ['effective_at'], unique=False)
    op.create_table('hypotheses',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('narrative', sa.String(length=4096), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'superseded', 'confirmed', 'rejected', name='hypothesisstatus', native_enum=False, length=64), nullable=False),
    sa.Column('generation_context', sa.JSON(), nullable=False),
    sa.Column('superseded_by_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_case_id'), 'hypotheses', ['case_id'], unique=False)
    op.create_table('uncertainty_flags',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('flag_type', sa.Enum('missing', 'stale', 'duplicate', 'contradictory', name='uncertaintyflagtype', native_enum=False, length=64), nullable=False),
    sa.Column('related_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uncertainty_flags_case_id'), 'uncertainty_flags', ['case_id'], unique=False)
    op.create_index(op.f('ix_uncertainty_flags_flag_type'), 'uncertainty_flags', ['flag_type'], unique=False)
    op.create_table('approvals',
    sa.Column('action_request_id', sa.String(), nullable=False),
    sa.Column('required_role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False, length=64), nullable=False),
    sa.Column('decided_by_user_id', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_requests.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_action_request_id'), 'approvals', ['action_request_id'], unique=False)
    op.create_table('evidence_links',
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('evidence_record_id', sa.String(), nullable=False),
    sa.Column('relation', sa.Enum('supports', 'weakens', name='evidencerelation', native_enum=False, length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_record_id'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_links_evidence_record_id'), 'evidence_links', ['evidence_record_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_hypothesis_id'), 'evidence_links', ['hypothesis_id'], unique=False)
    op.create_table('impact_assessments',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=True),
    sa.Column('financial_exposure_usd', sa.Float(), nullable=False),
    sa.Column('sla_breach_score', sa.Float(), nullable=False),
    sa.Column('customer_tier_weight', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_assessments_case_id'), 'impact_assessments', ['case_id'], unique=False)
    op.create_table('tool_executions',
    sa.Column('action_request_id', sa.String(), nullable=False),
    sa.Column('connector', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'timeout', name='toolexecutionstatus', native_enum=False, length=64), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_action_request_id'), 'tool_executions', ['action_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_executions_action_request_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_impact_assessments_case_id'), table_name='impact_assessments')
    op.drop_table('impact_assessments')
    op.drop_index(op.f('ix_evidence_links_hypothesis_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_evidence_record_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_approvals_action_request_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_uncertainty_flags_flag_type'), table_name='uncertainty_flags')
    op.drop_index(op.f('ix_uncertainty_flags_case_id'), table_name='uncertainty_flags')
    op.drop_table('uncertainty_flags')
    op.drop_index(op.f('ix_hypotheses_case_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_canonical_events_effective_at'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_case_id'), table_name='canonical_events')
    op.drop_table('canonical_events')
    op.drop_index(op.f('ix_audit_entries_occurred_at'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_entity_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_case_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_actor_type'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_action_requests_idempotency_key'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_case_id'), table_name='action_requests')
    op.drop_table('action_requests')
    op.drop_index(op.f('ix_evidence_records_source_type'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_order_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_occurred_at'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_ingested_at'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_external_ref'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_customer_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_cases_order_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_customer_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_external_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
