"""add ingest pipeline tables

Revision ID: ba9ae356323d
Revises: 9350c570ff24
Create Date: 2026-09-01 13:48:09.353253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9ae356323d'
down_revision: Union[str, None] = '9350c570ff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_dead_letters',
    sa.Column('raw_event', sa.JSON(), nullable=False),
    sa.Column('error_reason', sa.String(length=1024), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_outbox',
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_outbox_aggregate_id'), 'ingest_outbox', ['aggregate_id'], unique=False)
    op.create_table('ingest_timelines',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', name='timelinestatus', native_enum=False, length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_timelines_customer_id'), 'ingest_timelines', ['customer_id'], unique=False)
    op.create_table('ingest_conflicts',
    sa.Column('timeline_id', sa.String(), nullable=False),
    sa.Column('fact_type', sa.String(length=128), nullable=False),
    sa.Column('resolution_status', sa.Enum('unresolved', 'resolved', name='conflictresolutionstatus', native_enum=False, length=64), nullable=False),
    sa.Column('resolution_rule', sa.String(length=128), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['ingest_timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_conflicts_timeline_id'), 'ingest_conflicts', ['timeline_id'], unique=False)
    op.create_table('ingest_orders',
    sa.Column('timeline_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('order_ref', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['ingest_timelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_ref', name='uq_ingest_orders_order_ref')
    )
    op.create_index(op.f('ix_ingest_orders_customer_id'), 'ingest_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ingest_orders_order_ref'), 'ingest_orders', ['order_ref'], unique=False)
    op.create_index(op.f('ix_ingest_orders_timeline_id'), 'ingest_orders', ['timeline_id'], unique=False)
    op.create_table('ingest_logs',
    sa.Column('timeline_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('source_system', sa.Enum('webapp', 'pos', 'oms', 'wms', 'payments', 'cc', 'returns', name='ingestsourcesystem', native_enum=False, length=64), nullable=False),
    sa.Column('fact_type', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ingest_orders.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['ingest_timelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timeline_id', 'order_id', 'source_system', 'fact_type', name='uq_log_identity')
    )
    op.create_index(op.f('ix_ingest_logs_customer_id'), 'ingest_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ingest_logs_fact_type'), 'ingest_logs', ['fact_type'], unique=False)
    op.create_index(op.f('ix_ingest_logs_order_id'), 'ingest_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_ingest_logs_source_system'), 'ingest_logs', ['source_system'], unique=False)
    op.create_index(op.f('ix_ingest_logs_timeline_id'), 'ingest_logs', ['timeline_id'], unique=False)
    op.create_table('ingest_order_versions',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.String(length=64), nullable=False),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ingest_orders.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['ingest_order_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'version_no', name='uq_order_version_no')
    )
    op.create_index(op.f('ix_ingest_order_versions_order_id'), 'ingest_order_versions', ['order_id'], unique=False)
    op.create_table('ingest_log_versions',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.String(length=64), nullable=False),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['ingest_logs.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['ingest_log_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id', 'version_no', name='uq_log_version_no')
    )
    op.create_index(op.f('ix_ingest_log_versions_log_id'), 'ingest_log_versions', ['log_id'], unique=False)
    op.create_table('ingest_conflict_references',
    sa.Column('conflict_id', sa.String(), nullable=False),
    sa.Column('log_version_id', sa.String(), nullable=True),
    sa.Column('order_version_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['ingest_conflicts.id'], ),
    sa.ForeignKeyConstraint(['log_version_id'], ['ingest_log_versions.id'], ),
    sa.ForeignKeyConstraint(['order_version_id'], ['ingest_order_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_conflict_references_conflict_id'), 'ingest_conflict_references', ['conflict_id'], unique=False)
    # ### end Alembic commands ###

    # --- Append-only enforcement for ingest_log_versions / ingest_order_versions ---
    # Postgres-only: SQLite has no trigger-level BEFORE UPDATE/DELETE RAISE
    # equivalent worth the portability cost, so append-only stays app-level
    # discipline in local dev (matches every other append-only guarantee in
    # this codebase, e.g. EvidenceRecord). On Postgres/Supabase this is a
    # genuine DB-enforced guarantee.
    #
    # Deliberately a trigger, not a GRANT/REVOKE on the connecting role: in
    # Postgres, REVOKE never restricts a table's OWNER, and the role this
    # migration runs as (and that the app currently connects as) owns these
    # tables -- a REVOKE here would silently do nothing. A trigger enforces
    # the invariant for every role, including the owner, and needs no new
    # cluster-level role provisioned via a migration against a managed
    # Supabase instance (a separate, higher-risk change -- see README).
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION ingest_reject_version_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION '% is append-only: % not permitted on id=%',
                    TG_TABLE_NAME, TG_OP, OLD.id;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        for table in ("ingest_log_versions", "ingest_order_versions"):
            op.execute(
                f"""
                CREATE TRIGGER {table}_append_only
                BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW EXECUTE FUNCTION ingest_reject_version_mutation();
                """
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for table in ("ingest_log_versions", "ingest_order_versions"):
            op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table};")
        op.execute("DROP FUNCTION IF EXISTS ingest_reject_version_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_conflict_references_conflict_id'), table_name='ingest_conflict_references')
    op.drop_table('ingest_conflict_references')
    op.drop_index(op.f('ix_ingest_log_versions_log_id'), table_name='ingest_log_versions')
    op.drop_table('ingest_log_versions')
    op.drop_index(op.f('ix_ingest_order_versions_order_id'), table_name='ingest_order_versions')
    op.drop_table('ingest_order_versions')
    op.drop_index(op.f('ix_ingest_logs_timeline_id'), table_name='ingest_logs')
    op.drop_index(op.f('ix_ingest_logs_source_system'), table_name='ingest_logs')
    op.drop_index(op.f('ix_ingest_logs_order_id'), table_name='ingest_logs')
    op.drop_index(op.f('ix_ingest_logs_fact_type'), table_name='ingest_logs')
    op.drop_index(op.f('ix_ingest_logs_customer_id'), table_name='ingest_logs')
    op.drop_table('ingest_logs')
    op.drop_index(op.f('ix_ingest_orders_timeline_id'), table_name='ingest_orders')
    op.drop_index(op.f('ix_ingest_orders_order_ref'), table_name='ingest_orders')
    op.drop_index(op.f('ix_ingest_orders_customer_id'), table_name='ingest_orders')
    op.drop_table('ingest_orders')
    op.drop_index(op.f('ix_ingest_conflicts_timeline_id'), table_name='ingest_conflicts')
    op.drop_table('ingest_conflicts')
    op.drop_index(op.f('ix_ingest_timelines_customer_id'), table_name='ingest_timelines')
    op.drop_table('ingest_timelines')
    op.drop_index(op.f('ix_ingest_outbox_aggregate_id'), table_name='ingest_outbox')
    op.drop_table('ingest_outbox')
    op.drop_table('ingest_dead_letters')
    # ### end Alembic commands ###
